// Fallback data for local development when D1 is not available
// This data matches the seed data structure

export const fallbackPortfolio = [
  {
    id: 'port-001',
    title: 'E-Commerce Fashion Store',
    category: 'E-Commerce',
    description: 'Modern online store for Filipino fashion brand with inventory management',
    client: 'StyleHub Manila',
    imageUrl: null,
    liveUrl: null,
    technologies: '["Next.js","Shopify","Tailwind CSS"]',
    results: null,
    testimonial: null,
    order: 1,
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'port-002',
    title: 'Restaurant Booking System',
    category: 'Web Application',
    description: 'Online reservation system with real-time table availability',
    client: 'Sarap Dine',
    imageUrl: null,
    liveUrl: null,
    technologies: '["React","Node.js","PostgreSQL"]',
    results: null,
    testimonial: null,
    order: 2,
    isActive: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'port-003',
    title: 'Healthcare Portal',
    category: 'SaaS Platform',
    description: 'Patient management system for medical clinics',
    client: 'MedCare Philippines',
    imageUrl: null,
    liveUrl: null,
    technologies: '["Vue.js","Laravel","MySQL"]',
    results: null,
    testimonial: null,
    order: 3,
    isActive: true,
    createdAt: new Date('2024-02-15'),
  },
];

export const fallbackFeatures = [
  {
    id: 'feat-001',
    title: 'AI-Powered PRD Generation',
    description: 'Get comprehensive project requirements in under 30 seconds using advanced AI',
    icon: 'Sparkles',
    order: 1,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'feat-002',
    title: 'Real-Time Project Tracking',
    description: 'Monitor your project progress 24/7 through our intuitive dashboard',
    icon: 'BarChart3',
    order: 2,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'feat-003',
    title: 'Flexible Payment Options',
    description: 'Pay with GCash, PayMaya, or cards - split into two convenient payments',
    icon: 'CreditCard',
    order: 3,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'feat-004',
    title: 'Direct Client Communication',
    description: 'Message your team directly through the platform - no email chains',
    icon: 'MessageSquare',
    order: 4,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'feat-005',
    title: 'Automated Documentation',
    description: 'All project requirements, tasks, and timeline generated automatically',
    icon: 'FileText',
    order: 5,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'feat-006',
    title: 'Fast Turnaround Time',
    description: 'Most projects completed in 2-4 weeks, not months',
    icon: 'Zap',
    order: 6,
    isActive: true,
    createdAt: new Date(),
  },
];

export const fallbackServices = [
  {
    id: 'svc-001',
    name: 'Landing Page',
    description: 'Professional single-page website perfect for showcasing your business, product, or service',
    basePrice: 15000,
    features: '["Responsive design (mobile, tablet, desktop)","Up to 5 sections","Contact form integration","Basic SEO optimization","Social media links","1 round of revisions","30 days support"]',
    timeline: '1-2 weeks',
    popular: false,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'svc-002',
    name: 'Business Website',
    description: 'Multi-page website ideal for established businesses with multiple services or products',
    basePrice: 35000,
    features: '["Up to 10 pages","Responsive design","Content Management System (CMS)","Blog functionality","Advanced SEO","Google Analytics integration","Contact forms","2 rounds of revisions","60 days support"]',
    timeline: '2-4 weeks',
    popular: true,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'svc-003',
    name: 'E-Commerce Website',
    description: 'Full-featured online store with payment integration for selling products online',
    basePrice: 75000,
    features: '["Product catalog with categories","Shopping cart functionality","Payment gateway integration (PayMongo, GCash, PayMaya)","Inventory management","Order tracking system","Customer accounts","Admin dashboard","Mobile responsive","SSL certificate","3 rounds of revisions","90 days support"]',
    timeline: '4-8 weeks',
    popular: false,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'svc-004',
    name: 'Web Application',
    description: 'Custom web application tailored to your specific business needs and workflows',
    basePrice: 150000,
    features: '["Custom functionality development","User authentication & roles","Database design & integration","API development","Admin dashboard","Real-time features","Third-party integrations","Scalable architecture","Security best practices","Unlimited revisions","180 days support"]',
    timeline: '6-12 weeks',
    popular: false,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'svc-005',
    name: 'Mobile App',
    description: 'Native iOS and Android applications with seamless user experience',
    basePrice: 200000,
    features: '["Cross-platform development (iOS & Android)","Native performance","Push notifications","Offline functionality","In-app purchases","Analytics integration","App store submission","Custom UI/UX design","Backend API development","Unlimited revisions","1 year support"]',
    timeline: '8-16 weeks',
    popular: false,
    isActive: true,
    createdAt: new Date(),
  },
];

export const fallbackProcess = [
  {
    id: 'proc-001',
    title: 'Tell Us Your Vision',
    description: 'Fill out our simple onboarding form with your project details. Takes only 5 minutes.',
    order: 1,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'proc-002',
    title: 'Get Instant PRD & Quote',
    description: 'Our AI generates a comprehensive Project Requirements Document and accurate pricing in under 30 seconds.',
    order: 2,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'proc-003',
    title: 'Review & Confirm',
    description: 'Review the automated task breakdown, timeline, and pricing. Request any adjustments needed.',
    order: 3,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'proc-004',
    title: 'Development Begins',
    description: 'Make your deposit and we start building immediately. Track progress in your dashboard 24/7.',
    order: 4,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'proc-005',
    title: 'Launch & Support',
    description: 'After final review and full payment, we deploy your project and provide ongoing support.',
    order: 5,
    isActive: true,
    createdAt: new Date(),
  },
];

export const fallbackFaqs = [
  {
    id: 'faq-001',
    question: 'How long does it take to complete a project?',
    answer: 'Most projects are completed within 2-4 weeks, depending on complexity. Landing pages can be ready in 7-10 days, while complex web applications may take 4-6 weeks. We provide a detailed timeline during the initial consultation.',
    order: 1,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-002',
    question: 'What payment methods do you accept?',
    answer: 'We accept GCash, PayMaya, bank transfer, and credit/debit cards through PayMongo. Payment is split into two: 50% deposit to start, 50% upon project completion.',
    order: 2,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-003',
    question: 'Do you offer revisions?',
    answer: 'Yes! All packages include revisions. The number varies by package (2-3 rounds for basic packages, unlimited for premium). We want you to be 100% satisfied with the final result.',
    order: 3,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-004',
    question: 'Will my website work on mobile devices?',
    answer: 'Absolutely! All our websites are fully responsive and optimized for mobile, tablet, and desktop devices. Mobile-first design is our standard practice.',
    order: 4,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-005',
    question: 'Do you provide hosting and domain setup?',
    answer: 'Yes, we include free hosting for 1 year with most packages. We can also help you register a domain name or use your existing one. After the first year, hosting costs are minimal (₱2,000-5,000/year).',
    order: 5,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-006',
    question: 'Can I update the website myself after launch?',
    answer: "Yes! For websites with CMS integration (content management system), you'll be able to update text, images, and blog posts yourself. We provide training and documentation.",
    order: 6,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-007',
    question: 'What if I need changes after the project is completed?',
    answer: 'We offer ongoing support packages starting at ₱3,000/month for minor updates and maintenance. Major feature additions can be quoted separately.',
    order: 7,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'faq-008',
    question: 'How does your AI-powered process work?',
    answer: 'After you fill out our onboarding form, our AI generates a comprehensive Project Requirements Document and task breakdown in under 30 seconds. This ensures nothing is missed and gives you a clear picture of the entire project upfront.',
    order: 8,
    isActive: true,
    createdAt: new Date(),
  },
];
