name = "lunaxcode-saas"
compatibility_date = "2024-10-11"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "lunaxcode-dev"
database_id = "" # Fill this after running: wrangler d1 create lunaxcode-dev

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "lunaxcode-files"

[vars]
ENVIRONMENT = "development"
